# BEGIN_KITTY_THEME
include VSCode_Dark.conf
font_family CaskaydiaCove Nerd Font
cursor_shape block
window_padding_width 10
font_size 12
shell_integration disabled
confirm_os_window_close 2
# cursor_beam_thickness 1.5
no-cursor
# END_KITTY_THEME
