source = ~/.config/hypr/colors/catppuccin-latte.conf

general {
    # See https://dark.hyprland.org/Configuring/Variables/ for more

    gaps_in = 5
    gaps_out = 6
    border_size = 2
    col.active_border = $pink $pink 45deg
    col.inactive_border = rgba(286983cc)

    layout = dwindle

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false
}

decoration {
    # See https://wiki.hyprland.org/Configuring/Variables/ for more

    rounding = 8
    
    blur {
        enabled = true
        size = 6
        passes = 1
    }

    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    layerrule=blur
    # col.shadow = rgba(1a1a1aee)
}
