# windowrulev2 = nomaximizerequest, class:.* # You'll probably like this.
windowrulev2 = opacity 0.90 0.90,class:^(kitty)$
windowrulev2 = opacity 0.90 0.90,class:(codium-url-handler)$
# file manager
windowrulev2 = opacity 0.90 0.90,class:(nemo)$
windowrulev2 = opacity 0.90 0.90,class:(WebCord)$
