# clock mode
setw -g clock-mode-colour #f6c177

# copy mode
setw -g mode-style 'fg=#e0def4 bg=#6e6a87 bold'

# panes
set -g pane-border-style 'fg=#6e6a87'
set -g pane-active-border-style 'fg=#f6c177'

# statusbar
set -g status-style 'fg=#e0def4 bg=#26233a'

setw -g window-status-current-style 'fg=#e0def4 bg=#524f67'
setw -g window-status-style 'fg=#908caa bg=#26233a'
setw -g window-status-bell-style 'fg=#d8a657 bg=#ea6962 bold'

# messages
set -g message-style 'fg=#e0def4 bg=#1f1d2e bold'
