# clock mode
setw -g clock-mode-colour #eed49f

# copy mode
setw -g mode-style 'fg=#cad3f5 bg=#24273a bold'

# panes
set -g pane-border-style 'fg=#b8c0e0'
set -g pane-active-border-style 'fg=#a6da95'

# statusbar
set -g status-style 'fg=#24273a bg=#a6da95'

setw -g window-status-current-style 'fg=#24273a bg=#8aadf4'

setw -g window-status-style 'fg=#24273a'
setw -g window-status-bell-style 'fg=#eed49f bg=#ed8796 bold'

# messages
set -g message-style 'fg=#b8c0e0 bg=#6e738d bold'
