format = "$username $directory $git_branch $fill $time $cmd_duration\n  [󱞪](fg:blue) "

[directory]
format = "[](fg:black)[ $path ]($style)[](fg:black)"
style = "bg:black fg:purple"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
Documents = "󰈙"
Downloads = " "
Music = " "
Pictures = " "

[fill]
style = "fg:black"
symbol = " "

[git_branch]
format = "[](fg:black)[ $symbol $branch ]($style)[](fg:black)"
style = "bg:black fg:bright-yellow"
symbol = ""

[time]
disabled = false
format = "[](fg:black)[ $time 󰴈 ]($style)[](fg:black)"
style = "bg:black fg:bright-cyan"
time_format = "%I:%M%P"
use_12hr = true

[username]
disabled = false
format = "[](fg:black)[ 󰌽 $user ]($style)[](fg:black)"
show_always = true
style_root = "bg:black fg:red"
style_user = "bg:black fg:blue"

[cmd_duration]
format = "[](fg:black)[  took $duration ]($style)[](fg:black)"
style = "bg:black fg:bright-cyan"
min_time = 500
